import type { Metadata } from "next";
import { montserrat400 } from "../fonts/montserrat";
export const metadata: Metadata = {
    title: "Wallets",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${montserrat400.className} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
